=== CS174/Hw5/XML/info_card.dtd
<!ELEMENT info_card (people+)>
<!ELEMENT people (name, address, response)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT response (#PCDATA)>

=== CS174/Hw5/XML/test.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE info_card SYSTEM "info_card.dtd" >

<info_card >
    <people>
        <name> sophia </name>
        <address> san jose </address>
        <response> yes </response>
    </people>
    <people>
        <name> jhon </name>
        <address> san francisco </address>
        <response> yes </response>
    </people>
</info_card>
